from .facultad_escuela_selector import FacultadEscuelaSelector
from .facultad_x_grupo_selector import FacultadXGrupoSelector
from .gerente_selector import GerenteSelector
from .grado_estudios_selector import GradoEstudiosSelector
from .grupo_investigacion_selector import GrupoInvestigacionSelector
from .persona_selector import PersonaSelector
from .persona_x_grupo_selector import PersonaXGrupoSelector
from .rol_grupo_selector import RolGrupoSelector