# Generated by Django 5.2.7 on 2026-07-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_historial_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentofirma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentofirma',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='documentofirma',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('info', 'Información'), ('exito', 'Éxito'), ('alerta', 'Alerta'), ('error', 'Error')], max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='documentofirma',
            unique_together={('tipo_documento', 'content_type', 'object_id', 'version')},
        ),
        migrations.AddIndex(
            model_name='documentofirma',
            index=models.Index(fields=['content_type', 'object_id'], name='common_docu_content_5460a1_idx'),
        ),
    ]
