# Generated by Django 5.2.7 on 2026-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_documentofirma_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofirma',
            name='fecha_ultima_verificacion_integridad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofirma',
            name='integridad_ok',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
