# Generated by Django 5.2.7 on 2026-09-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_documentofirma_fecha_ultima_verificacion_integridad_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='es_obligatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='investigacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
