# Generated by Django 5.2.7 on 2026-09-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_tipodocumento_es_obligatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='investigacion',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('formativa', 'Formativa')], max_length=10, null=True),
        ),
    ]
