# Generated by Django 5.2.7 on 2026-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_tipodocumento_investigacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='es_acta_inicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='es_informe_seguimiento',
            field=models.BooleanField(default=False),
        ),
    ]
