# Generated by Django 5.2.7 on 2026-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('tipo_relacion', models.CharField(choices=[('FINANCIADOR', 'Financiador'), ('COOPERANTE', 'Cooperante')], max_length=50)),
            ],
            options={
                'verbose_name': 'Entidad Externa',
                'verbose_name_plural': 'Entidades Externas',
            },
        ),
        migrations.CreateModel(
            name='IndicadorImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_nombre', models.CharField(max_length=100)),
                ('valor_proyectado', models.FloatField()),
                ('valor_real', models.FloatField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicador de Impacto',
                'verbose_name_plural': 'Indicadores de Impacto',
                'ordering': ['-ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(choices=[('REUNION', 'Reunión'), ('CONVENIO', 'Firma Convenio')], max_length=50)),
                ('resumen', models.TextField()),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
