# Generated by Django 5.2.7 on 2026-06-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('investigacion_formal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorimpacto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto'),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.entidadexterna'),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='proyecto_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigacion_formal.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='indicadorimpacto',
            unique_together={('proyecto', 'kpi_nombre')},
        ),
    ]
