# Generated by Django 5.2.7 on 2026-07-26 01:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('investigacion_formal', '0002_alter_tipocalificacion_ordenfase_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicadorimpacto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='indicadorimpacto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('kpi_nombre'), models.F('proyecto'), name='uq_indicador_proyecto_kpi_lower'),
        ),
    ]
