# Generated by Django 5.2.7 on 2026-06-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('institucional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_convocatoria', models.CharField(max_length=200, unique=True)),
                ('anio_convocatoria', models.IntegerField()),
                ('inicio', models.DateField()),
                ('cierre', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('interno', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMinciencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo_minciencias', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMinciencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, unique=True)),
                ('nomenclatura', models.CharField(max_length=20, unique=True)),
                ('peso', models.IntegerField()),
                ('vigencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=255, unique=True)),
                ('peso', models.FloatField(default=0)),
                ('completado', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol_investigador', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calificacion', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('evaluacion', models.BooleanField(default=False)),
                ('ordenFase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(max_length=200, unique=True)),
                ('aplica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rubro', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoXGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_minciencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.grupominciencias')),
                ('producto_minciencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.productominciencias')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.tipoproducto')),
            ],
            options={
                'unique_together': {('producto_minciencias', 'grupo_minciencias', 'tipo_producto')},
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=2000, unique=True)),
                ('interno', models.BooleanField()),
                ('registro_acta_cierre', models.BooleanField()),
                ('alianza', models.BooleanField()),
                ('estado', models.BooleanField()),
                ('estado_aprobado', models.CharField(max_length=255)),
                ('financiado', models.BooleanField()),
                ('unidad_ejecutora', models.CharField(max_length=10)),
                ('linea_investigacion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('gruplac', models.BooleanField(default=False)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.gerente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'gerente')},
            },
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255, unique=True)),
                ('clase', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Monto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado', models.FloatField(default=0)),
                ('aprobado', models.FloatField(blank=True, null=True)),
                ('asignado', models.DateField(blank=True, null=True)),
                ('ejecutado', models.FloatField(blank=True, null=True)),
                ('contrapartida', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ControlCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(max_length=255)),
                ('fecha_cambio', models.DateField(blank=True, null=True)),
                ('cambio_tiempo', models.BooleanField(default=False, verbose_name='Tiempo')),
                ('cambio_investigador', models.BooleanField(default=False, verbose_name='Investigador')),
                ('cambio_costo', models.BooleanField(default=False, verbose_name='Costo')),
                ('cambio_producto', models.BooleanField(default=False, verbose_name='Producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoXConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('estado_finalizado_calificacion', models.BooleanField(default=False)),
                ('ultimo_filtro_calificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobacion_ultima_calificacion', models.BooleanField(default=False)),
                ('calificacion_ultimo_filtro_calificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('modificacion_documento_proyecto', models.BooleanField(default=False)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.convocatoria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto')),
            ],
            options={
                'unique_together': {('convocatoria', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('monto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.monto')),
                ('tipo_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.tiporubro')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoXProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('entregado', models.BooleanField()),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(max_length=30)),
                ('puntaje', models.IntegerField()),
                ('gruplac', models.BooleanField(default=False)),
                ('producto_x_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.productoxgrupo')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.tipodocumento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto')),
            ],
            options={
                'unique_together': {('producto_x_grupo', 'proyecto', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='ObjetivoXPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_avance', models.CharField(max_length=255)),
                ('avance', models.FloatField(default=0)),
                ('mes_avance', models.CharField(max_length=20)),
                ('anio_avance', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.objetivos')),
                ('punto_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.puntocontrol')),
            ],
            options={
                'unique_together': {('objetivo', 'punto_control')},
            },
        ),
        migrations.CreateModel(
            name='InvestigadorXProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcid', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('persona_x_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.personaxgrupo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyecto')),
                ('rol_investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.rolinvestigador')),
            ],
            options={
                'unique_together': {('rol_investigador', 'proyecto', 'persona_x_grupo')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=1000)),
                ('aprobado', models.BooleanField(default=False)),
                ('primer_sin_observacion', models.BooleanField(default=False)),
                ('aplicar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.proyectoxconvocatoria')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion_formal.tipocalificacion')),
            ],
            options={
                'unique_together': {('fase', 'aplicar')},
            },
        ),
    ]
