# Generated by Django 5.2.7 on 2026-07-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion_formal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocalificacion',
            name='ordenFase',
            field=models.IntegerField(db_column='ordenFase'),
        ),
        migrations.RenameField(
            model_name='tipocalificacion',
            old_name='ordenFase',
            new_name='orden_fase',
        ),
    ]
