# Generated by Django 5.2.7 on 2026-07-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion_formal', '0002_alter_tipocalificacion_ordenfase_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set(),
        ),
    ]
