# Generated by Django 5.2.7 on 2026-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion_formal', '0003_alter_proyecto_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objetivoxpunto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='objetivoxpunto',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', True)), fields=('objetivo', 'punto_control'), name='objetivo_x_punto_unico_activo'),
        ),
    ]
