# Generated by Django 5.2.7 on 2026-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion_formal', '0004_alter_objetivoxpunto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporubro',
            name='aplica',
            field=models.BooleanField(default=False),
        ),
    ]
