# Generated by Django 5.2.7 on 2026-09-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion_formal', '0005_tiporubro_aplica'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoxproyecto',
            unique_together={('producto_x_grupo', 'proyecto')},
        ),
        migrations.RemoveField(
            model_name='productoxproyecto',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='productoxproyecto',
            name='tipo_documento',
        ),
    ]
