# Generated by Django 5.2.7 on 2026-09-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_alter_personaxgrupo_unique_together_and_more'),
        ('investigacion_formal', '0006_alter_productoxproyecto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='facultad',
            field=models.ForeignKey(blank=True, help_text="Solo aplica si 'grupo_investigacion' es transversal a varias facultades (ver FacultadXGrupo), p.ej. Ciencias Militares.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_externos', to='institucional.facultadescuela'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='grupo_investigacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_externos', to='institucional.grupoinvestigacion'),
        ),
    ]
