from .facultad_escuela_validator import FacultadEscuelaValidator
from .facultad_x_grupo_validator import FacultadXGrupoValidator
from .gerente_validator import GerenteValidator
from .grado_estudios_validator import GradoEstudiosValidator
from .grupo_investigacion_validator import GrupoInvestigacionValidator
from .persona_validator import PersonaValidator
from .persona_x_grupo_validator import PersonaXGrupoValidator
from .rol_grupo_validator import RolGrupoValidator