# Generated by Django 5.2.7 on 2026-06-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuarioxpersona',
            name='unique_active_assignment_per_user',
        ),
        migrations.RenameField(
            model_name='usuarioxpersona',
            old_name='is_active',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='rolxusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usuarioxpersona',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', True)), fields=('usuario',), name='unique_active_assignment_per_user'),
        ),
    ]
