# Generated by Django 5.2.7 on 2026-07-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuarioxpersona_unique_active_assignment_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
    ]
