# Generated by Django 5.2.7 on 2026-09-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta cuenta (ej. Facultad). Permite que cada Facultad gestione solo las cuentas que ella misma creó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
