# Generated by Django 5.2.7 on 2026-06-02 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultadEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=30, unique=True)),
                ('abreviatura', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradoEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_grado', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=50, unique=True)),
                ('sigla_grupo', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('cvlac', models.CharField(blank=True, max_length=150, null=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.gradoestudios')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.persona')),
            ],
        ),
        migrations.CreateModel(
            name='FacultadXGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.facultadescuela')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.grupoinvestigacion')),
            ],
            options={
                'unique_together': {('grupo', 'facultad')},
            },
        ),
        migrations.CreateModel(
            name='PersonaXGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('desvinculacion', models.DateField(blank=True, null=True)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.facultadescuela')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.grupoinvestigacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.persona')),
                ('rol_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.rolgrupo')),
            ],
            options={
                'unique_together': {('persona', 'rol_grupo', 'grupo', 'facultad')},
            },
        ),
    ]
