# Generated by Django 5.2.7 on 2026-07-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaxgrupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grupoinvestigacion',
            name='clasificacion_grupo',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='personaxgrupo',
            constraint=models.UniqueConstraint(condition=models.Q(('grupo__isnull', False)), fields=('persona', 'rol_grupo', 'grupo'), name='uq_persona_rol_grupo'),
        ),
        migrations.AddConstraint(
            model_name='personaxgrupo',
            constraint=models.UniqueConstraint(condition=models.Q(('facultad__isnull', False), ('grupo__isnull', True)), fields=('persona', 'rol_grupo', 'facultad'), name='uq_persona_rol_facultad'),
        ),
        migrations.AddConstraint(
            model_name='personaxgrupo',
            constraint=models.UniqueConstraint(condition=models.Q(('facultad__isnull', True), ('grupo__isnull', True)), fields=('persona', 'rol_grupo'), name='uq_persona_rol_administrativo'),
        ),
    ]
