from .facultad_escuela_serializer import FacultadEscuelaSerializer
from .facultad_x_grupo_serializer import FacultadXGrupoSerializer
from .gerente_serializer import GerenteSerializer
from .grado_estudios_serializer import GradoEstudiosSerializer
from .grupo_investigacion_serializer import GrupoInvestigacionSerializer
from .persona_x_grupo_serializer import PersonaXGrupoSerializer
from .persona_serializer import PersonaSerializer
from .rol_grupo_serializer import RolGrupoSerializer