"""
Django settings for rosillo project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # ojo: ahora hay un nivel más

# Cargar variables de entorno desde el archivo .env
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken', # App para la autenticación por Token
    'axes', # Para bloqueo de intentos de login
    'corsheaders',
    'django_recaptcha', # Para validación de reCAPTCHA
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    # MIS APPS MODULARES
    'apps.common.apps.CommonConfig',
    'apps.crm',
    'apps.integracion',
    'apps.institucional',
    'apps.investigacion_formal',
    'apps.investigacion_formativa',
    'apps.usuarios',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')]},
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'axes.middleware.AxesMiddleware', # Middleware de django-axes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usar variables de entorno para la configuración de la base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5433'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# --- Static ---
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []  # déjalo vacío si no tienes una carpeta /static propia en la raíz

# --- Media ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Rutas específicas de documentos (equivalente a RutasDocument.java del Thymeleaf)
DOCUMENTOS_ROOT = Path(os.getenv('DOCUMENTOS_ROOT', r'C:\RUTA_DOCUMENTOS_ROSILLO'))
CONVOCATORIA_ROOT = DOCUMENTOS_ROOT / 'CONVOCATORIA'
PRESUPUESTO_ROOT = DOCUMENTOS_ROOT / 'PRESUPUESTO'
PROYECTO_ROOT = DOCUMENTOS_ROOT / 'PROYECTO'
TRABAJO_GRADO_ROOT = DOCUMENTOS_ROOT / 'TRABAJO_GRADO'
PLANTILLAS_ROOT = DOCUMENTOS_ROOT / 'PLANTILLAS'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- MODELO DE USUARIO PERSONALIZADO ---
AUTH_USER_MODEL = 'usuarios.Usuario'
GESTION_USUARIO_SERVICE = 'apps.integracion.services.vinculacion_service.VinculacionService'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Por defecto, solo usuarios autenticados pueden acceder a la API
    ],
    # Protección contra DoS (Denial of Service) - Throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',
        'user': '100/min',
        'login': '5/min',
    },
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
SIMPLE_JWT.update({
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
})

# --- CONFIGURACIÓN DE SEGURIDAD ADICIONAL ---
# 1. Backend de Autenticación Personalizado (Equivalente a UsuarioServicioImpl)
# Django buscará primero en el backend por defecto y luego en el nuestro.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend', # Backend de Axes para registrar intentos
#    'apps.usuarios.authentication.CustomAuthBackend', # NUESTRO backend personalizado
    'django.contrib.auth.backends.ModelBackend', # Puedes mantener el de Django si lo necesitas
]

# 2. Configuración de django-axes (Equivalente a LoginAttemptService)
AXES_FAILURE_LIMIT = 5 # Máximo 5 intentos fallidos, al 6 intento se bloquea
AXES_COOLOFF_TIME = 1 # Bloquea por 1 hora
AXES_LOCKOUT_CALLABLE = 'config.axes_handlers.lockout_response' # Opcional: una plantilla para mostrar si está bloqueado
AXES_USERNAME_FORM_FIELD = 'username' # El campo del formulario que contiene el username

# AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_RESET_ON_SUCCESS = True
AXES_ENABLE_ADMIN = False

# 3. Protección CSRF y XSS (Cross-Site Request Forgery y Cross-Site Scripting)
# Django ya tiene protección CSRF y XSS activada por defecto a través de sus middlewares y sistema de plantillas.
# Para una API REST, la protección CSRF es menos relevante si usas autenticación por Token,
# pero estas cabeceras de seguridad adicionales son buenas prácticas.
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# 4. Protección contra DoS (Denial of Service)
# La configuración se ha integrado en el diccionario REST_FRAMEWORK más arriba
# para limitar la tasa de peticiones (Throttling).

# 5. Configuración de Correo Electrónico (Equivalente a spring.mail.*)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'notificacionesrosillo@esmic.edu.co')
EMAIL_SOPORTE = os.getenv('EMAIL_SOPORTE', 'notificacionesrosillo@esmic.edu.co')
PQRS_SUBJECT_PREFIX = "Solicitud de soporte"

# 5.1 Configuración de Celery (colas de tareas asíncronas — envío de
# correo y job de recordatorios de tareas)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Si una tarea falla tras agotar reintentos, no debe reventar al caller
# (mismo criterio de tolerancia que tenía el try/except silencioso
# original); el error queda logueado desde la tarea, no propagado.
CELERY_TASK_EAGER_PROPAGATES = False

from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    'enviar-recordatorios-tareas-diario': {
        'task': 'apps.common.tasks.enviar_recordatorios_tareas_task',
        'schedule': crontab(hour=7, minute=0),  # todos los días 7:00 a.m.
    },
    'verificar-integridad-documentos-diario': {
        'task': 'apps.common.tasks.verificar_integridad_documentos_task',
        'schedule': crontab(hour=2, minute=0),  # fuera de horario laboral
    },
}

# 6. Límite de tamaño de Archivos (Equivalente a spring.servlet.multipart.*)
# El valor está en bytes. 100MB = 100 * 1024 * 1024 = 104857600 bytes.
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600
DIA_LIMITE_INFORME_SEGUIMIENTO = int(os.getenv('DIA_LIMITE_INFORME_SEGUIMIENTO', '25'))

# --- CONFIGURACIÓN PARA CORS ---
# Cada ambiente define su propio CORS_ALLOWED_ORIGINS vía .env (ver
# local.py/development.py/stage.py/production.py). base.py deja un
# default vacío a propósito, para que ningún ambiente herede por error
# el origen de desarrollo (localhost:3000) si alguien olvida configurarlo.
CORS_EXPOSE_HEADERS = ['Content-Disposition']
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# --- CONFIGURACIÓN DE RECAPTCHA ---
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

# --- Sesiones (equivalente a server.servlet.session.timeout=15m) ---
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_AGE = 1200  # 20 minutos en segundos
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # cada request reinicia el contador de 20 min
CSRF_COOKIE_HTTPONLY = False
SECURE_BROWSER_XSS_FILTER = False

# --- Logging ---
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Desactiva django-axes durante `python manage.py test` para que los
# tests de login/permisos de distintas apps no se bloqueen entre sí
# por acumular intentos fallidos contra la misma IP del test client.
if 'test' in sys.argv:
    AXES_ENABLED = False
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['login'] = None
    AMBITO_CHECK_PERMISIVO_SIN_AUTH = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_general': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_errors': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'level': 'ERROR',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file_general'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}