# Generated by Django 5.2.7 on 2026-07-26 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_documentofirma_unique_together_and_more'),
        ('institucional', '0002_alter_personaxgrupo_unique_together_and_more'),
        ('investigacion_formativa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bancoideas',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postulacionproceso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='registroactividades',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificacionexterna',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etapaflujo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoevaluativo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registroactividades',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actividadformativa',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('ELIMINADA', 'Eliminada')], default='PLANIFICADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='bancoideas',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('SEPARADA', 'Separada'), ('TOMADA', 'Tomada'), ('ELIMINADA', 'Eliminada')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantrabajo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ELIMINADO', 'Eliminado')], default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='postulacionproceso',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('EN_VALIDACION', 'En validación de requisitos'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ELIMINADA', 'Eliminada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bancoideas',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ELIMINADA'), _negated=True), fields=('facultad', 'idea'), name='banco_ideas_unica_facultad_idea_activa'),
        ),
        migrations.AddConstraint(
            model_name='postulacionproceso',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ELIMINADA'), _negated=True), fields=('estudiante', 'modalidad'), name='postulacion_unica_estudiante_modalidad_activa'),
        ),
        migrations.AddConstraint(
            model_name='registroactividades',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proceso', 'registrado_por', 'fecha_periodo'), name='registro_actividades_unico_periodo_activo'),
        ),
    ]
