# Generated by Django 5.2.7 on 2026-07-28 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_alter_personaxgrupo_unique_together_and_more'),
        ('investigacion_formativa', '0002_alter_bancoideas_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bancoideas',
            name='separada_por',
            field=models.ForeignKey(blank=True, help_text='Persona que actualmente tiene esta idea separada/tomada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_separadas', to='institucional.persona'),
        ),
    ]
