# Generated by Django 5.2.7 on 2026-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion_formal', '0005_tiporubro_aplica'),
        ('investigacion_formativa', '0003_alter_estudiante_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procesoformativoxproyecto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='procesoformativoxproyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='procesoformativoxproyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proceso_formativo', 'proyecto_formal'), name='vinculo_proceso_proyecto_unico_activo'),
        ),
    ]
