from .facultad_escuela_service import FacultadEscuelaService
from .facultad_x_grupo_service import FacultadXGrupoService
from .gerente_service import GerenteService
from .grado_estudios_service import GradoEstudiosService
from .grupo_investigacion_service import GrupoInvestigacionService
from .persona_service import PersonaService
from .persona_x_grupo_service import PersonaXGrupoService
from .rol_grupo_service import RolGrupoService